apiVersion: apps/v1
kind: Deployment

metadata:
  name: memories-backend
  namespace: memories-prod

spec:
  replicas: 2

  strategy:

    type: RollingUpdate

    rollingUpdate:

      maxSurge: 1

      maxUnavailable: 0
      
  selector:
    matchLabels:
      app: memories-backend

  template:

    metadata:
      labels:
        app: memories-backend

    spec:

      containers:
      - name: backend

        image: jaydipaws/memories-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000


        resources:

          requests:
            cpu: "50m"
            memory: "64Mi"

          limits:
            cpu: "200m"
            memory: "256Mi"

        env:

        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: memories-config
              key: PORT

        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: memories-config
              key: NODE_ENV

        - name: CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: memories-secret
              key: CONNECTION_URL
          
        readinessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3