apiVersion: apps/v1
kind: Deployment

metadata:
  name: memories-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: memories-backend

  template:

    metadata:
      labels:
        app: memories-backend

    spec:

      containers:
      - name: backend

        image: jaydipaws/memories-backend:latest
        ports:
        - containerPort: 5000


        resources:

          requests:
            cpu: "50m"
            memory: "64Mi"

          limits:
            cpu: "200m"
            memory: "256Mi"

        env:

        - name: CONNECTION_URL
          value: mongodb://mongo-service:27017/memories
          
        readinessProbe:

          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3