apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: memories-prod
  
spec:

  type: ClusterIP

  selector:
    app: memories-backend

  ports:

  - port: 5000

    targetPort: 5000