apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: memories-mongo
  namespace: memories-prod
  
spec:

  serviceName: mongo-service

  replicas: 1

  selector:
    matchLabels:
      app: memories-mongo

  template:

    metadata:
      labels:
        app: memories-mongo

    spec:

      containers:

      - name: mongo

        image: mongo:7

        ports:

        - containerPort: 27017